### ISSUE TITLE
v0.15.1无法使用

### ISSUE THREAD

**Issue by zhushiyo** [MisaLiu/nezha-theme-mdui#1]
可以适配一下v0.15.1吗

**Comment by MisaLiu** [comment]
![image](https://github.com/MisaLiu/nezha-theme-mdui/assets/62408957/e7c95e91-d45b-4528-ae05-f94373d8f176)

您好，本地测试 v0.15.1 版本的 Dashboard 可以正常使用主题，请您再检查一下您的面板配置
