### ISSUE TITLE
哪吒监控 v0.15.2 选择主题为 Custom(local) 时报错 前台主题文件异常：custom

### ISSUE THREAD

**Issue by HandingTo1** [MisaLiu/nezha-theme-mdui#2]
1.下载仓库到本地
2.复制本仓库的 theme-custom 文件夹，替换你面板所在服务器的 /opt/nezha/dashboard/theme-custom/ 文件夹
3.登陆面板后台，选择主题为 Custom(local) 这一步选择后 保存时提示 前台主题文件异常：custom

如图所示：
![74b02c4a699403929a0e1.png](https://telegra.ph/file/74b02c4a699403929a0e1.png)

**Comment by MisaLiu** [comment]
我目前在用 0.15.1，可能是更新到 0.15.2 的时候面板改动了什么东西，有时间看看

**Comment by HandingTo1** [comment]
> 我目前在用 0.15.1，可能是更新到 0.15.2 的时候面板改动了什么东西，有时间看看

好的，辛苦了

**Comment by HandingTo1** [comment]
> 我目前在用 0.15.1，可能是更新到 0.15.2 的时候面板改动了什么东西，有时间看看

15.5经测试替换文件夹后重启哪吒面板服务即可正常使用了。
